# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 03:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared_results', models.CharField(max_length=2)),
                ('is_disputed', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchRosterSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo_modifier', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm_base.Match')),
            ],
        ),
        migrations.CreateModel(
            name='MatchTeamSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(default=False)),
                ('invalid', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm_base.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_queued', models.BooleanField(default=False)),
                ('current_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='mm_base.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo', models.IntegerField(default=2500)),
                ('elo_weight', models.FloatField(default=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REPLACE_ME_mm_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=20)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain', to='mm_base.Player')),
                ('players', models.ManyToManyField(related_name='teams', to='mm_base.Player')),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='players',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_party', to='mm_base.Player'),
        ),
        migrations.AddField(
            model_name='party',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_party', to='mm_base.Team'),
        ),
        migrations.AddField(
            model_name='matchteamslot',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm_base.Team'),
        ),
        migrations.AddField(
            model_name='matchrosterslot',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm_base.Player'),
        ),
        migrations.AddField(
            model_name='matchrosterslot',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm_base.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(related_name='matches', through='mm_base.MatchRosterSlot', to='mm_base.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(related_name='matches', through='mm_base.MatchTeamSlot', to='mm_base.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to='mm_base.Team'),
        ),
    ]
